# Generated by Django 5.2.7 on 2025-12-01 08:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('isbn', models.CharField(help_text='국제 표준 도서 번호 (PK, NOT NULL)', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='도서명 (NOT NULL)', max_length=255)),
                ('author', models.CharField(blank=True, help_text='저자', max_length=50, null=True)),
                ('image_url', models.CharField(blank=True, help_text='도서 표지 이미지 URL', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(help_text='분류번호 (PK, 수동 입력)', primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='분류명 (UNIQUE, NOT NULL)', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_borrow_count', models.IntegerField(default=3, help_text='1인당 최대 대여 권수 (기본: 3권)', validators=[django.core.validators.MinValueValidator(1)])),
                ('default_due_days', models.IntegerField(default=14, help_text='기본 대여 기간 (기본: 14일)', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_extend_days', models.IntegerField(default=7, help_text='연장 가능 기간 (기본: 7일)', validators=[django.core.validators.MinValueValidator(1)])),
                ('overdue_penalty_days', models.IntegerField(default=7, help_text='연체 시 대여 정지 기간 (기본: 7일)', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '운영 정책',
                'verbose_name_plural': '운영 정책',
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(help_text='출판사번호 (PK)', primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(help_text='출판사명 (UNIQUE, NOT NULL)', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='출판사 연락처', max_length=20, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('login_id', models.CharField(help_text='로그인 아이디 (UNIQUE, NOT NULL)', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='이름 (NOT NULL)', max_length=150)),
                ('birth_date', models.DateField(help_text='생년월일 (NOT NULL)')),
                ('phone_number', models.CharField(help_text='휴대폰번호 (UNIQUE, NOT NULL)', max_length=20, unique=True)),
                ('status', models.CharField(default='정상', help_text="회원상태 (NOT NULL, DEFAULT '정상')", max_length=10)),
                ('overdue_end_date', models.DateField(blank=True, help_text='연체 종료일', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'member',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_manage_id', models.AutoField(help_text='도서관리번호 (PK, NOT NULL)', primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, '대여가능'), (1, '대여중'), (2, '대여불가')], default=0, help_text='도서상태 (0:대여가능, 1:대여중, 2:대여불가)')),
                ('isbn', models.ForeignKey(db_column='isbn', help_text='도서번호 (FK, NOT NULL)', on_delete=django.db.models.deletion.CASCADE, to='bookdb.bookinfo')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('borrow_id', models.AutoField(help_text='대여번호 (PK)', primary_key=True, serialize=False)),
                ('borrow_date', models.DateField(help_text='대여일 (NOT NULL)')),
                ('due_date', models.DateField(help_text='반납예정일 (NOT NULL)')),
                ('return_date', models.DateField(blank=True, help_text='실제반납일 (NULL이면 대여중)', null=True)),
                ('is_extended', models.BooleanField(default=False, help_text='연장 여부 (NOT NULL, DEFAULT false)')),
                ('book', models.ForeignKey(db_column='book_manage_id', help_text='도서관리번호 (FK, NOT NULL)', on_delete=django.db.models.deletion.PROTECT, to='bookdb.book')),
                ('member', models.ForeignKey(db_column='member_id', help_text='회원번호 (FK, NOT NULL)', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borrow',
            },
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', help_text='도서분류번호 (FK)', null=True, on_delete=django.db.models.deletion.PROTECT, to='bookdb.category'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='publisher',
            field=models.ForeignKey(blank=True, db_column='publisher_id', help_text='출판사번호 (FK)', null=True, on_delete=django.db.models.deletion.PROTECT, to='bookdb.publisher'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(help_text='리뷰번호 (PK)', primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(help_text='평점 (1~5, NOT NULL)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True, help_text='리뷰 내용', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일시 (NOT NULL, DEFAULT CURRENT_TIMESTAMP)')),
                ('isbn', models.ForeignKey(db_column='isbn', help_text='도서번호 (FK, NOT NULL)', on_delete=django.db.models.deletion.CASCADE, to='bookdb.bookinfo')),
                ('member', models.ForeignKey(db_column='member_id', help_text='회원번호 (FK, NOT NULL)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
