# Generated by Django 5.2.7 on 2025-12-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
